// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUUnfIa_0efCmiBN7iHaeuyVbhSaERJnU',
    appId: '1:597396034504:web:7727ef3fbfc7046c88e6fd',
    messagingSenderId: '597396034504',
    projectId: 'goalquest-ed5f8',
    authDomain: 'goalquest-ed5f8.firebaseapp.com',
    storageBucket: 'goalquest-ed5f8.firebasestorage.app',
    measurementId: 'G-D0BYE6K5XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRJfGGiOGzY-We_8jv5ercYhPLcPNzvDM',
    appId: '1:597396034504:android:6f595c4154d1c1ec88e6fd',
    messagingSenderId: '597396034504',
    projectId: 'goalquest-ed5f8',
    storageBucket: 'goalquest-ed5f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJYytqXkilKaiQLo6g1H_rF_TXfBCFTRk',
    appId: '1:597396034504:ios:f1fa26de95fee5aa88e6fd',
    messagingSenderId: '597396034504',
    projectId: 'goalquest-ed5f8',
    storageBucket: 'goalquest-ed5f8.firebasestorage.app',
    iosBundleId: 'com.example.goalquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJYytqXkilKaiQLo6g1H_rF_TXfBCFTRk',
    appId: '1:597396034504:ios:f1fa26de95fee5aa88e6fd',
    messagingSenderId: '597396034504',
    projectId: 'goalquest-ed5f8',
    storageBucket: 'goalquest-ed5f8.firebasestorage.app',
    iosBundleId: 'com.example.goalquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUUnfIa_0efCmiBN7iHaeuyVbhSaERJnU',
    appId: '1:597396034504:web:7966ae3abedad8a588e6fd',
    messagingSenderId: '597396034504',
    projectId: 'goalquest-ed5f8',
    authDomain: 'goalquest-ed5f8.firebaseapp.com',
    storageBucket: 'goalquest-ed5f8.firebasestorage.app',
    measurementId: 'G-5MVKMFFKQT',
  );
}
