# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Keep Flutter's iOS settings
    flutter_additional_ios_build_settings(target)

    # Force a minimum iOS version (matches platform line)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end

  # --- gRPC fix for Xcode 16 ----
  # This will run after every `pod install`
  # and patch the problematic line in basic_seq.h
  files = Dir.glob('Pods/gRPC-*/src/core/lib/promise/detail/basic_seq.h')
  files.each do |file|
    text = File.read(file)
    new_text = text.gsub(
      'Traits::template CallSeqFactory',
      'Traits::CallSeqFactory'
    )
    if text != new_text
      puts "Patching gRPC basic_seq.h in #{file}"
      File.open(file, 'w') { |f| f.write(new_text) }
    end
  end
end

